other_movement = function(other_agents,daytime){if(daytime=="day"){other_agents <<- other_agents %>%
  mutate(possibilities = case_when(row==gridrows & !col%in%edgecol ~ 2,
                                   row==1 & !col%in%edgecol ~ 3,
                                   col==gridcols & !row%in%edgerow ~ 4,
                                   col==1 & !row%in%edgerow ~ 5,
                                   row==gridrows & col==gridcols ~ 6,
                                   row==gridrows & col==1 ~ 7,
                                   row==1 & col==gridcols ~ 8,
                                   row==1 & col==1 ~ 9,
                                   TRUE ~ 1),
         movement = case_when(possibilities==2 ~ as.numeric(sample(c(1:6),nrow(.),replace=T)),
                              possibilities==3 ~ as.numeric(sample(c(4:9),nrow(.),replace=T)),
                              possibilities==4 ~ as.numeric(sample(c(1,2,4,5,7,8),nrow(.),replace=T)),
                              possibilities==5 ~ as.numeric(sample(c(2,3,5,6,8,9),nrow(.),replace=T)),
                              possibilities==6 ~ as.numeric(sample(c(1,2,4,5),nrow(.),replace=T)),
                              possibilities==7 ~ as.numeric(sample(c(2,3,5,6),nrow(.),replace=T)),
                              possibilities==8 ~ as.numeric(sample(c(4,5,7,8),nrow(.),replace=T)),
                              possibilities==9 ~ as.numeric(sample(c(5,6,8,9),nrow(.),replace=T)),
                              TRUE ~ as.numeric(sample(c(1:9),nrow(.),replace=T))),
         row = case_when(movement==1 ~ row-1,
                         movement==2 ~ row-1,
                         movement==3 ~ row-1,
                         movement==7 ~ row+1,
                         movement==8 ~ row+1,
                         movement==9 ~ row+1,
                         TRUE ~ row),
         col = case_when(movement==1 ~ col-1,
                         movement==3 ~ col+1,
                         movement==4 ~ col-1,
                         movement==6 ~ col+1,
                         movement==7 ~ col-1,
                         movement==9 ~ col+1,
                         TRUE ~ col),
         location = paste(row,",",col,sep = ""))}
}